language: node_js
node_js:
  - "iojs"
  - "8"
cache:
  yarn: true
  directories:
  - node_modules

install: true

script:
  - npm run test
  - npm run build

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

notifications:
  email:
    on_failure: change

after_success: 'npm run coveralls'
